### ISSUE TITLE
May I ask if it is possible to add language options, Chinese and English

### ISSUE THREAD

**Issue by wyg520** [tenebo/Hitomi-Downloader-Mac#2]

**Comment by tenebo** [comment]
Because of the bug in the program, it does not load the user language. It will be fixed in the next version. However, you can still change the language. Please click the third top menu bar. Then click the button with F5. You can then see the combo box with the country flag—change language by clicking and selecting it.

**Comment by tenebo** [comment]
The first stable version came out. Please install it.
